src/Entity/Actualite.php
<?php

namespace App\Entity;

use App\Repository\ActualiteRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Utils\Utils;

use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=ActualiteRepository::class)
 * @Vich\Uploadable
 */
class Actualite
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $preview;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $contenu; 

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $publier;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $seo_titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $seo_description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $seo_meta;
    
    /**
     * @Vich\UploadableField(mapping="actualite_image", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_publication;

    /**
     * @Gedmo\Slug(fields={"titre"}, updatable=true, separator="-")
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $slug;
    
    public function __toString(){
        return $this->titre;
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getPreview(): ?string
    {
        return $this->preview;
    }

    public function setPreview(?string $preview): self
    {
        $this->preview = $preview;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(?string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getPublier(): ?bool
    {
        return $this->publier;
    }

    public function setPublier(?bool $publier): self
    {
        $this->publier = $publier;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getSeoTitre(): ?string
    {
        return $this->seo_titre;
    }

    public function setSeoTitre(?string $seo_titre): self
    {
        $this->seo_titre = $seo_titre;

        return $this;
    }

    public function getSeoDescription(): ?string
    {
        return $this->seo_description;
    }

    public function setSeoDescription(?string $seo_description): self
    {
        $this->seo_description = $seo_description;

        return $this;
    }

    public function getSeoMeta(): ?string
    {
        return $this->seo_meta;
    }

    public function setSeoMeta(?string $seo_meta): self
    {
        $this->seo_meta = $seo_meta;

        return $this;
    }

    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;
        if ($image) {
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function getDatePublication(): ?\DateTimeInterface
    {
        return $this->date_publication;
    }

    public function setDatePublication(?\DateTimeInterface $date_publication): self
    {
        $this->date_publication = $date_publication;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDateFormat(){

        return Utils::getDateFormating($this->date_publication->format('Y-m-d'),$local="fr");

    }
}

src/Entity/Page.php
<?php

namespace App\Entity;

use App\Repository\PageRepository;
use Doctrine\ORM\Mapping as ORM;

use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PageRepository::class)
 * @Vich\Uploadable
 */
class Page
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $preview;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $contenu;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $seo_titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $seo_description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $seo_keywords;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $publier;

    /**
     * @Vich\UploadableField(mapping="page_image", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\ManyToOne(targetEntity=Categorypage::class, inversedBy="pages")
     */
    private $categorie;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $position;

    public function __toString()
    {
        return $this->titre;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPreview(): ?string
    {
        return $this->preview;
    }

    public function setPreview(?string $preview): self
    {
        $this->preview = $preview;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(?string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getSeoTitre(): ?string
    {
        return $this->seo_titre;
    }

    public function setSeoTitre(?string $seo_titre): self
    {
        $this->seo_titre = $seo_titre;

        return $this;
    }

    public function getSeoDescription(): ?string
    {
        return $this->seo_description;
    }

    public function setSeoDescription(?string $seo_description): self
    {
        $this->seo_description = $seo_description;

        return $this;
    }

    public function getSeoKeywords(): ?string
    {
        return $this->seo_keywords;
    }

    public function setSeoKeywords(?string $seo_keywords): self
    {
        $this->seo_keywords = $seo_keywords;

        return $this;
    }

    public function getPublier(): ?bool
    {
        return $this->publier;
    }

    public function setPublier(?bool $publier): self
    {
        $this->publier = $publier;

        return $this;
    }

    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;
        if ($image) {
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function getEntity(){
        return $this;
    }

    public function getCategorie(): ?Categorypage
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorypage $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(?int $position): self
    {
        $this->position = $position;

        return $this;
    }
}

templates/Frontend/Render/_actualites_home.html.twig
{% if list_actualites is not empty %}
	<div class="actualites_home">
		<div class="container">
			<h2 class="titre_actualites_home">Actualités</h2>
			<div class="row">
				<div class="col-lg-1"></div>
				{% for actu in list_actualites %}
					<div class="col-lg-5 col-md-6">
						<div class="item_actualites_home">
							<h5><a href="{{ path('actualite_selected',{'slug':actu.slug}) }}">{{actu.titre}}</a></h5>
							<div class="lire_actu">
								<a href="{{ path('actualite_selected',{'slug':actu.slug}) }}">En savoir plus</a>
							</div>
						</div>
					</div>
				{% endfor %}
				<div class="col-lg-1"></div>
			</div>
		</div>
	</div>
{% endif %}

templates/Frontend/Render/_block_location_home.html.twig
<div class="block_location_home">
	<div class="container">
		<div class="row">
			<div class="col-lg-6">
				<div class="titre_location_home">
					<h3>
						<span>Location de</span>
						<span>mobilier de luxe</span>
						<span>sur mesure.</span>
					</h3>
				</div>
			</div>
			<div class="col-lg-6">
				<div class="text_location_home">
					<div>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eu mattis lectus. Integer dictum ante ante, nec gravida eros commodo quis. Donec in tristique felis, eu sodales urna. Praesent tellus leo, euismod et enim ut, pulvinar venenatis erat. Aliquam scelerisque tristique neque. Nulla nec pellentesque lacus. 
						</p>
						<a href="#">En savoir plus</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

templates/Frontend/Render/_categorie_home.html.twig
<div class="categories_home">
	<div class="container">
		<h2 class="titre_categories_home">Catégories</h2>

		{% if list_categories is not empty %}

            {% set collectionSize = 0 %}
            {% for categorie in list_categories %} 
            {% set collectionSize = collectionSize + 1 %}
            {% endfor %}


            {% set columnCount    = 4 %}
            {% set i              = 0 %} 
                 
            {% for categorie in list_categories %}

               
            {% if i % columnCount == 0  %}
            <div class="row">
            {% endif %} 

            {% set i = i + 1 %}  

            	<div class="col-lg-3 col-md-6 col-sm-6">
					<div class="item_categories_home">
						<a href="{{ path('categorie_selected',{'slug':categorie.slug}) }}">
                            {% if categorie.image is not empty %}
                                <img class="img-fluid img_categorie" src="{{ asset (vich_uploader_asset(categorie,'imageFile')) }}" alt="{{categorie.titre}}">
                            {% endif %}
                            {% if categorie.image2 is not empty %}
                                <img class="img-fluid img_categorie_hover" src="{{ asset (vich_uploader_asset(categorie,'image2File')) }}" alt="{{categorie.titre}}">
                            {% endif %}
                        </a>
						<h3><a href="{{ path('categorie_selected',{'slug':categorie.slug}) }}">{{categorie.titre}}</a></h3>
					</div>
				</div>

            {%  if i % columnCount == 0 or i == collectionSize %}
                </div>
            {% endif %}

            {% endfor %}
 

        {% else %}
            <p>
            	{{"Il n'y a aucune categorie pour l'instant."|trans}}
            </p>
        {% endif %}

	</div>
</div>

templates/Frontend/Render/_evenement_home.html.twig
<div class="evenement_home">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-md-6">
				<div class="img_evenement_home">
					<img class="img-fluid" src="{{ asset('assets/images/img_event_principale.jpg')}}" alt="Evenement">
				</div>
			</div>
			<div class="col-lg-6 col-md-6">
				<div class="text_evenement_home">
					<p>
						Votre événement a besoin d’une touche unique ? On s’en occupe de A à Z.
					</p>
					<a href="{{ path('contact_link') }}">Contactez-nous</a>
				</div>
			</div>
		</div>
		{% if list_evenements is not empty %}
			<div class="row row_slider_evenement">
				<div class="col-lg-1">
					<h2 class="titre_slider_evenement">Evenements</h2>
				</div>
				<div class="col-lg-11">
					<div class="slider_evenement owl-carousel owl-theme" id="slider_evenement">

						{% for event in list_evenements %}
							<div class="item_slider_evenement">
								<a href="{{ path('evenement_selected',{'slug':event.slug}) }}">
									<img class="img-fluid" src="{{ asset (vich_uploader_asset(event,'imageFile')) }}" alt="{{event.titre}}">
								</a>
								<h4><a href="{{ path('evenement_selected',{'slug':event.slug}) }}">{{event.titre}}</a></h4>
							</div>
						{% endfor %}

					</div>
				</div>
			</div>
		{% endif %}
	</div>
</div>

templates/Frontend/Render/_mediatheque_home.html.twig
{% if list_mediatheques is not empty %}
	<div class="mediatheque_home">
		<div class="container">
			<div class="titre_mediatheque_home">
				<h2><span>En images</span></h2>
			</div>
			<div class="list_medias">
				<div class="list_medias_grid">
					{% for media in list_mediatheques %}
						<div class="item_medias_grid">
							<div class="item_medias">
								<div class="zoom_gallery">
									<a href="{{ asset (vich_uploader_asset(media,'imageFile')) }}">
										<img class="img-fluid" src="{{ asset (vich_uploader_asset(media,'imageFile')) }}" alt="{{media.titre}}">
									</a>
								</div>
								<h5><a href="#">{{media.sousCategorie.titre}}</a></h5>
								<h6>{{media.titre}}</h6>
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
			<div class="mediatheque_plus">
				<div>
					<a href="{{ path('mediatheque') }}">Accéder à la médiathèque</a>
				</div>
			</div>
		</div>
	</div>
{% endif %}

templates/Frontend/Render/_pagination.html.twig
{% if pagination.nbPages > 0 %}
<section class="section-pagination">
    <ul class="pagination">
        {% if pagination.page > 1 %}
            <li>
                <a href="{{ path(pagination.nomRoute, pagination.paramsRoute|merge({'page': 1})) }}">
                    <<
                </a>
            </li>
            <li>
                <a href="{{ path(pagination.nomRoute,
                pagination.paramsRoute|merge({'page': pagination.page-1})) }}">
                    <
                </a>
            </li>
        {% endif %}

        {# Affichage de toutes les pages entre p-4 et p+4 sauf si < 1 ou > nbPages #}
        {% for p in range(max(pagination.page-4, 1), min(pagination.page+4, pagination.nbPages)) %}
            <li {% if p == pagination.page %}class="active"{% endif %}>
                <a href="{{ path(pagination.nomRoute, pagination.paramsRoute|merge({'page': p})) }}">
                    {{ p }}
                </a>
            </li>
        {% endfor %}

        {% if pagination.page < pagination.nbPages %}
            <li>
                <a href="{{ path(pagination.nomRoute,
                pagination.paramsRoute|merge({'page': pagination.page+1})) }}">
                    >
                </a>
            </li>
            <li>
                <a href="{{ path(pagination.nomRoute,
                pagination.paramsRoute|merge({'page': pagination.nbPages})) }}">
                    >>
                </a>
            </li>
        {% endif %}
    </ul>
</section>
{% endif %}

templates/Frontend/Render/_seo_sous_categorie.html.twig
<title>{{sous_categorie_selected.titre}}</title>

<meta name="title" content="{{sous_categorie_selected.seoTitre}}" />
<meta name="description" content="{{sous_categorie_selected.seoDescription}}" />
<meta name="keywords" content="{{sous_categorie_selected.seoKeywords}}" />  

<meta property="og:locale" content="fr_FR"/>
<meta property="og:site_name" content="https://"/>
<meta property="og:title" content="{{sous_categorie_selected.seoTitre}}"/>
<meta property="og:url" content="{{ absolute_url(path('sous_categorie_selected',{'cat_slug':categorie_selected.slug,'slug':sous_categorie_selected.slug}))}}"/>
<meta property="og:type" content="article"/>
<meta property="og:description" content="{{sous_categorie_selected.seoDescription}}"/>
<meta property="og:image" content="{{ absolute_url(asset(vich_uploader_asset(sous_categorie_selected,'imageFile')))}}"/> 
 
<meta name="twitter:title" content="{{sous_categorie_selected.seoTitre}}"/>
<meta name="twitter:url" content="https://"/>
<meta name="twitter:description" content="{{sous_categorie_selected.seoDescription}}"/>
<meta name="twitter:card" content="summary_large_image"/>

templates/Frontend/Render/_seoactualite.html.twig
<title>{{actualite_selected.titre}}</title>
<meta name="title" content="{{actualite_selected.seoTitre}}" />
<meta name="description" content="{{actualite_selected.seoDescription}}" />
<meta name="keywords" content="{{actualite_selected.seoMeta}}" />  

<meta property="og:locale" content="fr_FR"/>
<meta property="og:site_name" content="https://"/>
<meta property="og:title" content="{{actualite_selected.seoTitre}}"/>
<meta property="og:url" content="{{ absolute_url(path('actualite_selected',{'slug':actualite_selected.slug}))}}"/>
<meta property="og:type" content="article"/>
<meta property="og:description" content="{{actualite_selected.seoDescription}}"/>
<meta property="og:image" content="{% if actualite_selected.image is not empty %}{{ absolute_url(asset(vich_uploader_asset(actualite_selected,'imageFile')))}}{% endif %}"/> 
 
<meta name="twitter:title" content="{{actualite_selected.seoTitre}}"/>
<meta name="twitter:url" content="https://"/>
<meta name="twitter:description" content="{{actualite_selected.seoDescription}}"/>
<meta name="twitter:card" content="summary_large_image"/>

templates/Frontend/Render/_seoclient.html.twig
<title>{{client_selected.titre}}</title>

<meta name="title" content="{{client_selected.seoTitre}}" />
<meta name="description" content="{{client_selected.seoDescription}}" />
<meta name="keywords" content="{{client_selected.seoKeywords}}" />  

<meta property="og:locale" content="fr_FR"/>
<meta property="og:site_name" content="https://"/>
<meta property="og:title" content="{{client_selected.seoTitre}}"/>
<meta property="og:url" content="{{ absolute_url(path('client_selected',{'event_slug':evenement_selected.slug,'slug':client_selected.slug})) }}"/>
<meta property="og:type" content="article"/>
<meta property="og:description" content="{{client_selected.seoDescription}}"/>
<meta property="og:image" content="{{ absolute_url(asset(vich_uploader_asset(client_selected,'imageFile')))}}"/> 
 
<meta name="twitter:title" content="{{client_selected.seoTitre}}"/>
<meta name="twitter:url" content="https://"/>
<meta name="twitter:description" content="{{client_selected.seoDescription}}"/>
<meta name="twitter:card" content="summary_large_image"/>

templates/Frontend/Render/_seoevenement.html.twig
<title>{{evenement_selected.titre}}</title>

<meta name="title" content="{{evenement_selected.seoTitre}}" />
<meta name="description" content="{{evenement_selected.seoDescription}}" />
<meta name="keywords" content="{{evenement_selected.seoKeywords}}" />  

<meta property="og:locale" content="fr_FR"/>
<meta property="og:site_name" content="https://"/>
<meta property="og:title" content="{{evenement_selected.seoTitre}}"/>
<meta property="og:url" content="{{ absolute_url(path('evenement_selected',{'slug':evenement_selected.slug})) }}"/>
<meta property="og:type" content="article"/>
<meta property="og:description" content="{{evenement_selected.seoDescription}}"/>
<meta property="og:image" content="{{ absolute_url(asset(vich_uploader_asset(evenement_selected,'imageFile')))}}"/> 
 
<meta name="twitter:title" content="{{evenement_selected.seoTitre}}"/>
<meta name="twitter:url" content="https://"/>
<meta name="twitter:description" content="{{evenement_selected.seoDescription}}"/>
<meta name="twitter:card" content="summary_large_image"/>

templates/Frontend/Render/_seoheader.html.twig
<title></title>
<meta name="title" content="{{page_selected.seoTitre}}" />
<meta name="description" content="{{page_selected.seoDescription}}" />
<meta name="keywords" content="{{page_selected.seoDescription}}" />
<meta property="og:title" content="{{page_selected.seoTitre}}"/>
<meta property="og:url" content="https://diarysakane.ma"/>
<meta property="og:type" content="Page"/>
<meta property="og:image" content=""/>

templates/Frontend/Render/_switcher_categorie.html.twig
<div class="switcher_categorie switcher">
	<div class="container">
		<div class="row">
			<div class="col-lg-1 col-md-1"></div>
			<div class="col-lg-10 col-md-10">
				<div class="img_switcher">
					<img class="img-fluid" src="{{ asset ('assets/images/switcher_categorie.png') }}" alt="{{categorie_selected.titre}}">
					<div class="text_switcher">
						<div>
							<h1>{{categorie_selected.titre}}</h1>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-1 col-md-1"></div>
		</div>
	</div>
</div>

templates/Frontend/Render/_switcher_client.html.twig
<div class="switcher_categorie switcher">
	<div class="container">
		<div class="row">
			<div class="col-lg-1 col-md-1"></div>
			<div class="col-lg-10 col-md-10">
				<div class="img_switcher">
					<img class="img-fluid" src="{{ asset('assets/images/switcher_categorie.png') }}" alt="{{client_selected}}">
					<div class="text_switcher">
						<div>
							<h1>{{client_selected.titre}}</h1>
							<h2>{{client_selected.subTitre}}</h2>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-1 col-md-1"></div>
		</div>
	</div>
</div>

templates/Frontend/Render/_switcher_sous_categorie.html.twig
<div class="switcher_sous_categorie switcher">
	<div class="container">
		<div class="row">
			<div class="col-lg-1 col-md-1"></div>
			<div class="col-lg-10 col-md-10">
				<div class="img_switcher">
					<img class="img-fluid" src="{{ asset (vich_uploader_asset(sous_categorie_selected,'switcherFile')) }}" alt="{{sous_categorie_selected.titre}}">
					<div class="text_switcher">
						<div>
							<h1>{{sous_categorie_selected.titre}}</h1>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-1 col-md-1"></div>
		</div>
	</div>
</div>